### ISSUE TITLE
toml format for all chaosdorf location related things

### ISSUE THREAD

**Issue by ItsVipra** [chaosdorf/sonnenstr58#14]
# Origin
- e-lab hinten rechts = (0,0)
- bisheriger plan A1

# Definitions
- x axis: direction from street to lounge
- y-axis: direction from premium WC to entry
- z-axis: floor to ceiling

# Structure

Using areas to subdivide rooms into measurable chunks
hackcenter for example has many nooks and crannies that are easier to define with little quads

- Area
    - global x pos cm from origin
    - global y pos cm from origin
    - width: cm - on x-axis
    - depth: cm - on y-axis
    - comment
    - whatever you can think of
- room
  - Room name
    - area-ids[]
    - objects
      - tables-ids[]
      - whatever-furniture-ids[]
- door
    - area
    - opening direction

```toml
[areas.0]
number = 11
description = ""

dimensions.width = 69
dimensions.depth = 420
dimensions.height = 280

topleft.x = 0
topleft.y = 0

[areas.1]
#the next one


[rooms]
[rooms.Hackcenter]
areas = [1,2,3,4,5,56,69]
objects = []
objects.tables = [1,2,3]

[tables.1]


[shelf.1]
boxes = [156, 99]

[boxes.156]
content = ""
owner = "public"

```
